pull_request_rules:
  - name: backport patches to the release branch and assign to original author
    conditions:
      - label=backport/5.4
    actions:
      backport:
        branches:
          - "branch-5.4"
        assignees:
          - "{{ author }}"
