#
# Copyright (C) 2026-present ScyllaDB
#
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.1
#
"""Check that scylla exits cleanly under the sanitizers.

Debug/sanitize builds run with -fsanitize=address, which arms LeakSanitizer
at exit.  A leak reported at exit makes *every* invocation of the binary
fail - including a trivial `scylla --version` - regardless of what the
command actually did.  Such a regression does not come from Scylla code
only: pulling in a new shared library (a seastar submodule bump, a new
dependency in install-dependencies.sh) is enough, because that library's
ELF constructors run before main() and its allocations are attributed to
us.

That is what happened when Scylla started linking liblttng-ust: the
packaged binary could not print its version, and it was only caught much
later by a nightly Docker job running `scylla --version`.  These tests move
that check into the normal test framework so it fails on the commit that
introduces it.

The sanitizer options mirror exactly what the packaged `bin/scylla` wrapper
generated by install.sh exports, so a third-party leak that is *knowingly*
suppressed there is accepted here too, and anything else is a failure.
"""

import os
import subprocess

import pytest

from test import ALL_MODES, DEBUG_MODES, TOP_SRC_DIR


# Short-lived invocations handled by main()'s preinit block: they print
# something and return before the reactor is even started, so the whole suite
# is cheap even in debug mode and only the process exit path is exercised.
EXIT_IMMEDIATELY_FLAGS = ["--version", "--build-id", "--build-mode", "--list-tools"]

# Markers a sanitizer prints on the way out.  The leading "ERROR: " forms are
# emitted by ASan/LSan/UBSan; "runtime error:" is UBSan in non-halting mode.
SANITIZER_MARKERS = [
    "ERROR: AddressSanitizer",
    "ERROR: LeakSanitizer",
    "ERROR: ThreadSanitizer",
    "ERROR: UndefinedBehaviorSanitizer",
    "SUMMARY: AddressSanitizer",
    "SUMMARY: UndefinedBehaviorSanitizer",
    "runtime error:",
]


def suppressions_option(name: str) -> str:
    """`suppressions=<path>` for a top-level .supp file, empty if there is none.

    The files are optional so that this suite keeps working on branches that
    ship only some of them.
    """
    path = TOP_SRC_DIR / name
    return f":suppressions={path}" if path.is_file() else ""


@pytest.fixture(scope="module")
def sanitizer_env() -> dict[str, str]:
    """Environment matching the one install.sh bakes into bin/scylla.

    Keep this in sync with adjust_bin() in install.sh: the point of the suite
    is that the dev-tree binary is held to the same standard as the packaged
    one, so a leak that would break the package breaks the tests first.
    """
    env = dict(os.environ)
    env["ASAN_OPTIONS"] = "disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1"
    env["UBSAN_OPTIONS"] = "halt_on_error=1:abort_on_error=1" + suppressions_option("ubsan-suppressions.supp")
    env["LSAN_OPTIONS"] = "detect_leaks=1" + suppressions_option("lsan-suppressions.supp")
    return env


@pytest.mark.parametrize("flag", EXIT_IMMEDIATELY_FLAGS)
def test_exits_cleanly(scylla_binary: str,
                       sanitizer_env: dict[str, str],
                       scale_timeout,
                       flag: str) -> None:
    """`scylla <flag>` prints its answer, exits 0 and reports no sanitizer error."""
    res = subprocess.run([scylla_binary, flag],
                         capture_output=True,
                         text=True,
                         env=sanitizer_env,
                         timeout=scale_timeout(120))
    output = res.stdout + res.stderr

    found = [marker for marker in SANITIZER_MARKERS if marker in output]
    assert not found, (
        f"'{os.path.basename(scylla_binary)} {flag}' triggered {', '.join(found)}.\n"
        f"If the report comes from a third-party library that cannot be fixed, add a\n"
        f"suppression to the matching .supp file at the top of the source tree.  It\n"
        f"only takes effect on the packaged binary if it is also added to\n"
        f"scripts/create-relocatable-package.py and installed and exported by\n"
        f"install.sh - see how ubsan-suppressions.supp is handled.\n"
        f"Full output:\n{output}"
    )
    # LeakSanitizer's default exitcode is 23, so an unclean exit here is
    # usually a leak whose report was swallowed; check it after the marker
    # assertion, which gives the more informative message.
    assert res.returncode == 0, f"exited with {res.returncode}, output:\n{output}"
    assert output.strip(), "printed nothing at all"


def test_runs_the_binary_of_the_requested_mode(scylla_binary: str,
                                               sanitizer_env: dict[str, str],
                                               scale_timeout) -> None:
    """Guard against the suite silently degrading into a no-op.

    The tests above are only worth anything when they exercise a build that
    actually has the sanitizers armed, i.e. one of DEBUG_MODES.  Report which
    build we really ran, so a run that silently tests nothing is visible.

    The binary is not necessarily the one built for `build_mode` - with
    --exe-path the suite runs against a relocatable package instead, which is
    exactly how the packaged bin/scylla wrapper gets covered.
    """
    res = subprocess.run([scylla_binary, "--build-mode"],
                         capture_output=True,
                         text=True,
                         env=sanitizer_env,
                         timeout=scale_timeout(120))
    res.check_returncode()
    reported = res.stdout.strip()
    assert reported in ALL_MODES, f"unrecognized build mode {reported!r}"
    if reported not in DEBUG_MODES:
        pytest.skip(f"{reported} is not built with sanitizers; only the plain exit check applies")
