set(disabled_warnings
  c++11-narrowing
  mismatched-tags
  overloaded-virtual
  unsupported-friend)
include(CheckCXXCompilerFlag)
foreach(warning ${disabled_warnings})
  check_cxx_compiler_flag("-Wno-${warning}" _warning_supported_${warning})
  if(_warning_supported_${warning})
    list(APPEND _supported_warnings ${warning})
  endif()
endforeach()
list(TRANSFORM _supported_warnings PREPEND "-Wno-")
string(JOIN " " CMAKE_CXX_FLAGS
  "-Wall"
  "-Werror"
  "-Wno-error=deprecated-declarations"
  "-Wimplicit-fallthrough"
  ${_supported_warnings})

function(default_target_arch arch)
  set(x86_instruction_sets i386 i686 x86_64)
  if(CMAKE_SYSTEM_PROCESSOR IN_LIST x86_instruction_sets)
    set(${arch} "westmere" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
    # we always use intrinsics like vmull.p64 for speeding up crc32 calculations
    # on the aarch64 architectures, and they require the crypto extension, so
    # we have to add "+crypto" in the architecture flags passed to -march. the
    # same applies to crc32 instructions, which need the ARMv8-A CRC32 extension
    # please note, Seastar also sets -march when compiled with DPDK enabled.
    set(${arch} "armv8-a+crc+crypto" PARENT_SCOPE)
  else()
    set(${arch} "" PARENT_SCOPE)
  endif()
endfunction()

default_target_arch(target_arch)
if(target_arch)
    string(APPEND CMAKE_CXX_FLAGS " -march=${target_arch}")
endif()

math(EXPR _stack_usage_threshold_in_bytes "${stack_usage_threshold_in_KB} * 1024")
set(_stack_usage_threshold_flag "-Wstack-usage=${_stack_usage_threshold_in_bytes}")
check_cxx_compiler_flag(${_stack_usage_threshold_flag} _stack_usage_flag_supported)
if(_stack_usage_flag_supported)
  string(APPEND CMAKE_CXX_FLAGS " ${_stack_usage_threshold_flag}")
endif()

set(pgo_opts "")
# Clang supports three instrumenttation methods for profile generation:
# - -fprofile-instr-generate: this happens in the frontend (AST phase)
# - -fprofile-generate: this happens in the middle end. this intruments the LLVM IR
#   generated by the front-end. and is called the regular PGO.
# - -fcs-profile-generate: "cs" is short for Context Sensitive. this instrumentation
#   method is called CSPGO in comparision with the regular PGO above.
# We use IR and CSIR to represent the last two instrumentation methods in the option
# of Scylla_BUILD_INSTRUMENTED. the frontend instrumentation is not supported, because
# the IR-based instrumentation is superier than the frontend-based instrumentation when
# profiling executable for optimization purposes.
set(Scylla_BUILD_INSTRUMENTED OFF CACHE STRING
    "Build ScyllaDB with PGO instrumentation. May be specified as IR, CSIR")
if(Scylla_BUILD_INSTRUMENTED)
  file(TO_NATIVE_PATH "${CMAKE_BINARY_DIR}/${Scylla_BUILD_INSTRUMENTED}" Scylla_PROFILE_DATA_DIR)
  if(Scylla_BUILD_INSTRUMENTED STREQUAL "IR")
    # instrument code at IR level, also known as the regular PGO
    string(APPEND pgo_opts " -fprofile-generate=\"${Scylla_PROFILE_DATA_DIR}\"")
  elseif(Scylla_BUILD_INSTRUMENTED STREQUAL "CSIR")
    # instrument code with Context Sensitive IR, also known as CSPGO.
    string(APPEND pgo_opts " -fcs-profile-generate=\"${Scylla_PROFILE_DATA_DIR}\"")
  else()
    message(FATAL_ERROR "Unknown Scylla_BUILD_INSTRUMENTED: ${}")
  endif()
endif()

if(Scylla_BUILD_INSTRUMENTED)
  # options dependent on Scylla_BUILD_INSTRUMENTED
  set(Scylla_PROFDATA_FILE "" CACHE FILEPATH
    "Path to the profiling data file to use when compiling.")
  set(Scylla_PROFDATA_COMPRESSED_FILE
    "pgo/profiles/${CMAKE_SYSTEM_PROCESSOR}/profile.profdata.xz" CACHE FILEPATH
    "Path to the compressed profiling data file to use when compiling")
  if(Scylla_PROFDATA_FILE AND Scylla_PROFDATA_COMPRESSED_FILE)
    message(FATAL_ERROR
      "Both Scylla_PROFDATA_FILE and Scylla_PROFDATA_COMPRESSED_FILE are specified!")
  endif()
endif()

function(extract_compressed_file)
  find_program(XZCAT xzcat
    REQUIRED)

  cmake_parse_arguments(parsed_args "" "INPUT;OUTPUT" "" ${ARGN})
  set(input ${parsed_args_INPUT})

  get_filename_component(ext "${input}" LAST_EXT)
  get_filename_component(stem "${input}" NAME_WLE)
  set(output "${CMAKE_BINARY_DIR}/${stem}")
  if(ext STREQUAL ".xz")
    execute_process(
      COMMAND ${XZCAT} "${input}"
      OUTPUT_FILE "${output}"
      WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}")
  else()
    message(FATAL_ERROR "Unknown compression format: ${ext}")
  endif()
  set(${parsed_args_OUTPUT} ${output} PARENT_SCOPE)
endfunction(extract_compressed_file)

if(Scylla_PROFDATA_FILE)
  if(NOT EXISTS "${Scylla_PROFDATA_FILE}")
    message(FATAL_ERROR
      "Specified Scylla_PROFDATA_FILE (${Scylla_PROFDATA_FILE}) does not exist")
  endif()
  set(profdata_file "${Scylla_PROFDATA_FILE}")
elseif(Scylla_PROFDATA_COMPRESSED_FILE)
  # read the header to see if the file is fetched by LFS upon checkout
  file(READ "${Scylla_PROFDATA_COMPRESSED_FILE}" file_header LIMIT 7)
  if(file_header MATCHES "version")
    message(FATAL_ERROR "Please install git-lfs for using profdata stored in Git LFS")
  endif()
  extract_compressed_file(
    INPUT "${Scylla_PROFDATA_COMPRESSED_FILE}"
    OUTPUT "profdata_file")
endif()

if(profdata_file)
  if(Scylla_BUILD_INSTRUMENTED STREQUAL "IR")
    # -fprofile-use is not allowed with -fprofile-generate
    message(WARNING "Only CSIR supports using and generating profdata at the same time.")
    unset(pgo_opts)
  endif()
  # When building with PGO, -Wbackend-plugin generates a warning for every
  # function which changed its control flow graph since the profile was
  # taken.
  # We allow stale profiles, so these warnings are just noise to us.
  # Let's silence them.
  string(APPEND CMAKE_CXX_FLAGS " -Wno-backend-plugin")
  string(APPEND CMAKE_CXX_FLAGS " -fprofile-use=\"${profdata_file}\"")
endif()

if(pgo_opts)
  string(APPEND CMAKE_CXX_FLAGS "${pgo_opts}")
  string(APPEND CMAKE_EXE_LINKER_FLAGS "${pgo_opts}")
  string(APPEND CMAKE_SHARED_LINKER_FLAGS "${pgo_opts}")
endif()
