pull_request_rules:
  - name: backport patches to the release branch and assign to original author
    conditions:
      - label=backport
    actions:
      backport:
        branches:
          - "release-1.0"
          - "release-1.1"
        assignees:
          - "{{ author }}"
